### ISSUE TITLE
Marv attempting to insert audit record that already exists

### ISSUE THREAD

**Issue by EvanShaw** [guidesmiths/marv#26]
This may or may not be related to my other issue (https://github.com/guidesmiths/marv/issues/25), but I decided to split them up for clarity.

I have been using `marv` without issue creating migration files of the following form:
```
1.<comment>.sql
2.<comment>.sql
3.<comment>.sql
4.<comment>.sql
5.<comment>.sql
6.<comment>.sql
7.<comment>.sql
8.<comment>.sql
9.<comment>.sql
10.<comment>.sql
...
```
Until I got to level 10 and the following error occurs every migration attempt:
```
{ error: duplicate key value violates unique constraint "migrations_pkey"
    at Connection.parseE (/home/evan/workspace/go/src/bitbucket.org/ai-ot/ts-api-server-psql/sql/node_modules/pg/lib/connection.js:604:11)
    at Connection.parseMessage (/home/evan/workspace/go/src/bitbucket.org/ai-ot/ts-api-server-psql/sql/node_modules/pg/lib/connection.js:401:19)
    at Socket.<anonymous> (/home/evan/workspace/go/src/bitbucket.org/ai-ot/ts-api-server-psql/sql/node_modules/pg/lib/connection.js:121:22)
    at Socket.emit (events.js:198:13)
    at addChunk (_stream_readable.js:288:12)
    at readableAddChunk (_stream_readable.js:269:11)
    at Socket.Readable.push (_stream_readable.js:224:10)
    at TCP.onStreamRead (internal/stream_base_commons.js:94:17)
  name: 'error',
  length: 219,
  severity: 'ERROR',
  code: '23505',
  detail: 'Key (level, namespace)=(10, default) already exists.',
  hint: undefined,
  position: undefined,
  internalPosition: undefined,
  internalQuery: undefined,
  where: undefined,
  schema: 'public',
  table: 'migrations',
  column: undefined,
  dataType: undefined,
  constraint: 'migrations_pkey',
  file: 'nbtinsert.c',
  line: '433',
  routine: '_bt_check_unique',
  migration:
   { timestamp: 2019-10-21T08:50:46.110Z,
     checksum: '74675710329244c81b3ae39b06e32ff8',
     level: 10,
     comment: 'monthly settlement status tables',
     script:
      'CREATE TABLE IF NOT EXISTS monthly_settlement_status_shipper (\n    id BIGSERIAL PRIMARY KEY,\n    shippin...',
     directives: {},
     audit: undefined,
     namespace: 'default' } }
```
Once again, here are the records in my migrations table:
```
 id | level |                comment                |         timestamp          |             checksum             | namespace 
----+-------+---------------------------------------+----------------------------+----------------------------------+-----------
  1 |     1 | notifications nullable company id     | 2019-08-20 05:41:37.101+00 | d135296575397cc9d2fe0d92403e4543 | default
  2 |     2 | driver app truck location             | 2019-08-20 05:41:37.101+00 | f71cf2ff3d4e094602a120ba443d2cee | default
  3 |     3 | confirmed order nullable dates        | 2019-08-23 06:11:56.43+00  | b49a72ba25a2c745a5a03cc20b7a8100 | default
  4 |     4 | create shipper campaign all           | 2019-08-27 06:51:29.105+00 | 0086649384e43e75b17a1ee548694160 | default
  5 |     5 | create vendor campaign all            | 2019-08-27 06:51:29.105+00 | 232d3a976f070237f6454bfd8b99dc26 | default
  6 |     6 | create function is campaign available | 2019-08-27 06:51:29.105+00 | ba009c5496f3740aab63edd83ec183cf | default
  7 |     7 | chat notifications unreads join table | 2019-08-27 06:51:29.105+00 | a7baa5a718ab07a538298af905632e60 | default
  8 |     8 | add truck type transport vehicle      | 2019-09-20 07:22:36.289+00 | cd0716158637a36778e256e60a3d9632 | default
  9 |     9 | rewrite driver app tables             | 2019-09-24 03:17:50.613+00 | 977e2b520969b4505dff7ba1f36a392c | default
 10 |    10 | monthly settlement status tables      | 2019-09-27 06:58:39.149+00 | 74675710329244c81b3ae39b06e32ff8 | default
 16 |    11 | shipping company has insurance        | 2019-10-21 05:28:32.205+00 | 5da0f2793905e13176d83ec56711e5fc | default
 17 |    12 | order support level                   | 2019-10-21 05:28:32.205+00 | 232975a91b5fd1cd424ca4d9bb9d42bf | default
 18 |    13 | bank info drop notnull                | 2019-10-21 05:28:32.205+00 | d9a7dcc8a66c2398c1d0df9db6815e60 | default 
```
I don't know why `marv` is trying to insert an audit record that already exists. Adding `-- @MARV SKIP = true` as is written in the documentation bypasses the migration, but ever since then the problems described in my other issue (https://github.com/guidesmiths/marv/issues/25) occur. I'm not sure if they are related or not, but for whatever reason its seems that `marv` isn't aware of the audit record in this case.

Any help would be greatly appreciated.

**Comment by EvanShaw** [comment]
This issue was resolved via https://github.com/guidesmiths/marv/issues/25
