### ISSUE TITLE
XRegExp is not a function

### ISSUE THREAD

**Issue by benkeil** [guidesmiths/marv#36]
I got this error. In general this lib requires a lot of dependencies...

```
{
    "errorType": "TypeError",
    "errorMessage": "XRegExp is not a function",
    "stack": [
        "TypeError: XRegExp is not a function",
        "    at Object.<anonymous> (/var/task/webpack:/node_modules/marv/lib/scan.js:6:1)",
        "    at __webpack_require__ (/var/task/webpack:/webpack/bootstrap:19:1)",
        "    at Object.<anonymous> (/var/task/webpack:/node_modules/marv/api/callback.js:3:9)",
        "    at __webpack_require__ (/var/task/webpack:/webpack/bootstrap:19:1)",
        "    at Object.<anonymous> (/var/task/webpack:/node_modules/marv/api/promise.js:2:19)",
        "    at __webpack_require__ (/var/task/webpack:/webpack/bootstrap:19:1)",
        "    at Object.<anonymous> (/var/task/webpack:/src/entrypoints/run-database-migrations.ts:18:1)",
        "    at __webpack_require__ (/var/task/webpack:/webpack/bootstrap:19:1)",
        "    at /var/task/webpack:/webpack/bootstrap:83:1",
        "    at Object.<anonymous> (/var/task/index.js:88:10)"
    ]
}
```

**Comment by cressie176** [comment]
> I got this error

I suspect this is to do with how you're bundling marv / using webpack. If you google for "XRegExp is not a function" there are other issues indicating this.

> In general this lib requires a lot of dependencies

We disagree. Marv requires [5 dependencies](https://github.com/guidesmiths/marv/blob/master/package.json#L14-L18), not including the driver.
