### ISSUE TITLE
UnhandledPromiseRejectionWarning: error: at or near "lock": syntax error

### ISSUE THREAD

**Issue by danthegoodman1** [guidesmiths/marv#39]
Running `marv` with or without any migrations for CockroachDB throws the following error using the following script. I can see that the `migrations` and `migrations_lock` tables are created in my DB, but this seems to throw either way.

Script:

```
const path = require('path')
const driver = require('marv-pg-driver')
const marv = require('marv/api/promise')

async function main() {
  const dir = path.resolve('migrations')
  console.log(dir)
  const connection = {
    host: 'free-tier.gcp-us-central1.cockroachlabs.cloud',
    user: 'dan',
    database: 'portly-impala-2852.defaultdb',
    password: 'n6nYLf1v-nsnlK8M',
    port: 26257,
    ssl: {}
  }
  const migrations = await marv.scan(dir)
  await marv.migrate(migrations, driver({ connection }))
}

main()

```

Error:

```
/Users/dangoodman/clusterSpaceCode/meiliClustering/aAJS/migrations
  marv:scan Reading directory /Users/dangoodman/clusterSpaceCode/meiliClustering/aAJS/migrations +0ms
  marv:scan Ensuring that no files read in the directory were folders /Users/dangoodman/clusterSpaceCode/meiliClustering/aAJS/migrations +1ms
  marv:scan Reading file 001.migration.sql +0ms
  marv:migrate Connecting driver +0ms
  marv:pg-driver Connecting to postgres://dan:******@free-tier.gcp-us-central1.cockroachlabs.cloud:26257/portly-impala-2852.defaultdb +0ms
  marv:migrate Ensuring migrations +3s
  marv:pg-driver Ensure migrations +3s
  marv:migrate Unlocking migrations +94ms
(node:57302) UnhandledPromiseRejectionWarning: error: at or near "lock": syntax error
    at Parser.parseErrorMessage (/Users/dangoodman/clusterSpaceCode/meiliClustering/aAJS/node_modules/pg-protocol/dist/parser.js:287:98)
    at Parser.handlePacket (/Users/dangoodman/clusterSpaceCode/meiliClustering/aAJS/node_modules/pg-protocol/dist/parser.js:126:29)
    at Parser.parse (/Users/dangoodman/clusterSpaceCode/meiliClustering/aAJS/node_modules/pg-protocol/dist/parser.js:39:38)
    at TLSSocket.<anonymous> (/Users/dangoodman/clusterSpaceCode/meiliClustering/aAJS/node_modules/pg-protocol/dist/index.js:11:42)
    at TLSSocket.emit (events.js:315:20)
    at addChunk (internal/streams/readable.js:309:12)
    at readableAddChunk (internal/streams/readable.js:284:9)
    at TLSSocket.Readable.push (internal/streams/readable.js:223:10)
    at TLSWrap.onStreamRead (internal/stream_base_commons.js:188:23)
(Use `node --trace-warnings ...` to show where the warning was created)
```

**Comment by danthegoodman1** [comment]
(btw that is not the real password)

**Comment by cressie176** [comment]
Hi @danthegoodman1 ,
I suspect it's [this](https://github.com/guidesmiths/marv-pg-driver/blob/master/sql/lock-migrations-lock-table.sql#L2). My bet is the cockroachdb isn't fully compatible with PostgreSQL. If this is the case you would need a cockroach specific driver. They're usually pretty easy to write if you want to have a go.

**Comment by danthegoodman1** [comment]
Cockroachdb uses the Postgres driver, but maybe there is a sql command that’s slightly incompatible? They try really hard to be as postgres compatible as possible

**Comment by cressie176** [comment]
Cockroachdb's list of [statements](https://www.cockroachlabs.com/docs/v21.1/sql-statements) doesn't include PostgreSQL's [LOCK](https://www.postgresql.org/docs/14/sql-lock.html) statement. It therefore won't work with the marv-pg-driver. If you want to use marv with cockroachdb you will need to write a custom driver. You can use the existing [ones](https://github.com/guidesmiths/marv#drivers) as a reference and the [marv-compliance-tests](https://github.com/guidesmiths/marv-compliance-tests) to check it works correctly.
